### ISSUE TITLE
Can't build client for Windows

### ISSUE THREAD

**Issue by GREAT-DNG** [vircadia/vircadia-native-core#1767]
Hello, I am doing everything according to the [documentation](https://github.com/vircadia/vircadia-native-core/blob/master/BUILD_WIN.md). At the stage of generating build files I receive the following errors:
```
C:\Users\User\vircadia\build> cmake .. -G "Visual Studio 16 2019" -A x64
-- GLES_OPTION:
Using the Python interpreter located at: C:/Program Files/Python312/python.exe
['C:/Users/User/vircadia/prebuild.py', '--release-type', 'DEV', '--build-root', 'C:/Users/User/vircadia/build']
Using a packaged Qt
cmake path: C:\Users\User/vircadia-files/qt\qt5-install\lib\cmake
Fetching Qt from ['http://localhost:8080/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.vircadia.dev/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://gateway.ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://cloudflare-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh'] to C:\Users\User/vircadia-files/qt
Traceback (most recent call last):
  File "C:\Users\User\vircadia\prebuild.py", line 203, in <module>
    main()
  File "C:\Users\User\vircadia\prebuild.py", line 130, in main
    qt.installQt()
  File "C:\Users\User\vircadia\hifi_qt.py", line 221, in installQt
    hifi_utils.downloadAndExtract(self.qtUrl, self.path, self.qtSha512)
  File "C:\Users\User\vircadia\hifi_utils.py", line 139, in downloadAndExtract
    tempFileName = downloadFile(urls, hash, hasher)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\vircadia\hifi_utils.py", line 135, in downloadFile
    raise RuntimeError("Failed to download file from any of {} \nError Log:\n{}".format(urls, errorLog))
RuntimeError: Failed to download file from any of ['http://localhost:8080/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.vircadia.dev/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://gateway.ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://cloudflare-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh', 'https://ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh']
Error Log:
http://localhost:8080/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(ConnectionRefusedError(10061, '╧юфъы■ўхэшх эх єёЄрэютыхэю, Є.ъ. ъюэхўэ√щ ъюья№■ЄхЁ юЄтхЁу чряЁюё эр яюфъы■ўхэшх', None, 10061, None))
http://localhost:8080/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(ConnectionRefusedError(10061, '╧юфъы■ўхэшх эх єёЄрэютыхэю, Є.ъ. ъюэхўэ√щ ъюья№■ЄхЁ юЄтхЁу чряЁюё эр яюфъы■ўхэшх', None, 10061, None))
http://localhost:8080/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(ConnectionRefusedError(10061, '╧юфъы■ўхэшх эх єёЄрэютыхэю, Є.ъ. ъюэхўэ√щ ъюья№■ЄхЁ юЄтхЁу чряЁюё эр яюфъы■ўхэшх', None, 10061, None))
https://ipfs.vircadia.dev/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.vircadia.dev/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.vircadia.dev/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://gateway.ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://gateway.ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://gateway.ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cloudflare-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cloudflare-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://cloudflare-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.cf-ipfs.com/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
https://ipfs.io/ipfs/QmdRF8Pm5AmABAcqbdcp5ZMv4H4DF5orzgTg4BooDVAbCh: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))

CMake Error at CMakeLists.txt:151 (message):
  prebuild.py failed with error 1


-- Configuring incomplete, errors occurred!
```

The `HIFI_VCPKG_BASE` variable is set and the directory exists:
```
C:\Users\User\vircadia\build>echo %HIFI_VCPKG_BASE%
C:\Users\User\VCPKG
```

But no files appear in this directory.

I also tried all the actions in the [Troubleshooting](https://github.com/vircadia/vircadia-native-core/blob/master/BUILD_WIN.md#troubleshooting) section, but they had no effect.

How to fix this error?

**Comment by GREAT-DNG** [comment]
A workaround is to bypass SSL. To do this, in the `hifi_utils.py` file in line 115, replace the system name. Example for Windows:
```
if 'Windows' == platform.system():
```

**Comment by howaqw** [comment]
i think so
